server {
  listen 80;

  location /auth/ {
    proxy_pass http://auth-service:8000/;
  }

  location /tenant/ {
    proxy_pass http://tenant-service:8000/;
  }

  location /kms/ {
    proxy_pass http://kms-service:8000/;
  }

  location /broker/ {
    proxy_pass http://broker:9000/;
  }
}
